### ISSUE TITLE
nofollow and super table not work?

### ISSUE THREAD

**Issue by kos76** [codemonauts/craft-redactor-nofollow#1]
I use nofollow plugin for field type redactor and all is ok!
but if I try use nofollow plugin for super table with fields type redactor - nofollow not work.
after save entry link doesnt have attribute `rel="nofollow" `
how fix it?

**Comment by kos76** [comment]
I figured out why this happens - if the Purify HTML checkbox is set for the editor field, then the noufollw are replaced by noreferrer noopener

**Comment by kringkaste** [comment]
Sorry, we forgot to mention this in the documentation. You have to allow the "nofollow" in the rel attribute. The "norefferer noopener" is only set by HTMLPurifier if a target attribute is set. To not disable the hole HTMLPurifier in the richtext field, you can better add a custom config file to config/htmlpurifier. For example:

``` json
{
  "Attr.AllowedFrameTargets": ["_blank"],
  "Attr.EnableID": true,
  "HTML.AllowedComments": ["pagebreak"],
  "Attr.AllowedRel": ["nofollow"]
}
```

Save this to ```config/htmlpurifier/allowNoFollow.json```.

Then the changes from the plugin should not be wiped anymore. Be sure to have the first three config lines in the JSON, as these are the Craft defaults.
