### ISSUE TITLE
Critical bug - If Open in new Tab is selected, nofollow gets automatically selected

### ISSUE THREAD

**Issue by jonlongnecker** [codemonauts/craft-redactor-nofollow#2]
When using this plugin, nofollow gets automatically selected if "open in new tab" is selected. In this screenshot, I've only selected "open new tab", but after saving if I go back to edit, both items are selected.

This is a pretty big issue as there are plenty of times I'd like to open a link a new tab, but make sure it follows the link. But more importantly, it's specifically doing something I'm telling it not to do (re-selecting the option on save).

Craft CMS 3.4.10.1

**Comment by fleaz** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Critical Bug in no-follow Plugin](https://trello.com/c/lee1HjQJ/19-critical-bug-in-no-follow-plugin)

**Comment by kringkaste** [comment]
Hi @jonlongnecker thanks for reporting. I will investigate this.

**Comment by jonlongnecker** [comment]
Hey @kringkaste just checking in here - any luck with this yet?

**Comment by kringkaste** [comment]
Hey @jonlongnecker, I found the bug and fixed it. When you created a new link and saved the entry, the correct value of the attribute "rel" was saved ("nofollow" set or not set). Only if you edit an existing link the checkbox "nofollow" was always checked when the link also had the target "_blank".

Please update to the release 1.0.1.
