### ISSUE TITLE
Nofollow doesn't save

### ISSUE THREAD

**Issue by lucasvallenet** [codemonauts/craft-redactor-nofollow#3]
Hello,

I have a redactor field inside Neo.
When a link is added with the nofollow ticked, it automatically untick on entry save.
Is it compatible with Neo ?
I added the htmlpurifier config specified in this issue #1 but I doesn't solve the problem 

Versions:
Craft `3.5.11.1`
Neo `2.8.10`
Redactor `2.7.4`
No Follow `1.0.1`

**Comment by kringkaste** [comment]
Hello Lucas,

I just tested your issue with the following versions:

Craft 3.5.12.1
Neo 2.8.11
Redactor 2.8.1

and it works as expected. Can you check if you have selected your htmlpurifier config file in the advanced config section of the Redactor field?

**Comment by lucasvallenet** [comment]
Hi,
My bad, the config was selected in the wrong redactor field.
Thank you for your quick response!
