### ISSUE TITLE
Plugin not compatible with carlcs/craft-redactorcustomstyles

### ISSUE THREAD

**Issue by WHITE-developer** [codemonauts/craft-redactor-nofollow#6]
When installing both your plugin and carlcs/craft-redactorcustomstyles, we get an error in craft:
![image](https://user-images.githubusercontent.com/22771556/196153475-4c1c2f60-2f89-4841-96fa-18279c12d6e2.png)
This happens when we want to use "customstyles" plugin in a redactor setting.

Already asked the developer of carlcs/craft-redactorcustomstyles as well. He said it's on your end probably, otherwise let him know: https://github.com/carlcs/craft-redactorcustomstyles/issues/35

Craft CMS: 3.7.37
codemonauts/craft-redactor-nofollow: 1.0.1
carlcs/craft-redactorcustomstyles: 3.0.4

**Comment by WHITE-developer** [comment]
Any news on this?

**Comment by kringkaste** [comment]
Hi @WHITE-developer ! We fixed this in 1.0.2 for Craft CMS 3 and 2.1.0 for Craft CMS 4. Thanks for reporting it.
